functionsDirectory = "C:\\Users\\Patog\\linkguard\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Patog\\linkguard"
publishOrigin = "default"
functions = "C:\\Users\\Patog\\linkguard\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]